n=int(input())
lst=list(map(int,input().split()))
odd=0
even=0
positive=0
negative=0
for i in lst:
    if(i%2==0):
        even+=1
    else:
        odd+=1
    if(i>0):
        positive+=1
    elif(i<0):
        negative+=1
print("Even:",even)
print("Odd:",odd)
print("Positive:",positive)
print("Negative:",negative)